import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from '@/providers'
import { ToastContainer } from 'react-toastify'
import Header from '@/Layouts/Header'
import Footer from '@/Layouts/Footer'
import ScrollToTop from '@/components/ScrollToTop'
import RightMenu from '@/Layouts/RightMenu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ToastContainer />
        <Providers>
          <Header />
          <div className='ct-container min-h-dvh w-full py-10'>
            <div className='grid grid-cols-3 gap-20'>
              <div className='col-span-2 flex flex-col gap-10'>{children}</div>
              <RightMenu />
            </div>
          </div>

          <ScrollToTop />
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
